version: '3.3'

services:
    jekyll:
        image: jekyll/jekyll:3.8.6
        container_name: platform-ops
        command: jekyll serve --force_polling
        ports: ['4000:4000']
        volumes: ['.:/srv/jekyll']
