export class JhipsterGeneratorModel {
    constructor (
        public applicationType: string,
        public baseName: string,
        public packageName: string,
        public packageFolder: string,
        public serverPort: Number,
        public serviceDiscoveryType: any,
        public authenticationType: string,
        public uaaBaseName: string,
        public cacheProvider: string,
        public enableHibernateCache: boolean,
        public websocket: any,
        public databaseType: string,
        public devDatabaseType: string,
        public prodDatabaseType: string,
        public searchEngine: any,
        public enableSwaggerCodegen: any,
        public messageBroker: any,
        public buildTool: string,
        public useSass: Boolean,
        public clientPackageManager: string,
        public testFrameworks: string[],
        public enableTranslation: Boolean,
        public nativeLanguage: string,
        public languages: string[],
        public clientFramework: string,
        public jhiPrefix: string
    ) {}
}
